spring:
  application:
    name: news-microservice
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://mysql-ag-br1-20.conteige.cloud/ypuyuh_syncnews?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080
  servlet:
    context-path: /news-rest-api

management:
  endpoints:
    web:
      exposure:
        include: health

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
